# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: gfasales-scratch-pipeline
  path.config: "/usr/share/logstash/pipeline/gfasales-scratch.conf"

- pipeline.id: gfasales_incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/gfasales_incremental.conf"

- pipeline.id: product-quantity-pipeline
  path.config: "/usr/share/logstash/pipeline/product-quantity.conf"

- pipeline.id: loans-pipeline
  path.config: "/usr/share/logstash/pipeline/loans.conf"