# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: pgh-scratch-pipeline
  path.config: "/usr/share/logstash/pipeline/pgh-scratch.conf"

- pipeline.id: pgh-incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/pgh-incremental.conf"